# Generated by Django 4.2.7 on 2023-12-09 17:41

from django.db import migrations, models
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=lists.models.on_delete, to='lists.list'),
        ),
    ]
